package com.ddesign.foyer.login;

/**
 * Created by Alexandre on 30/10/2015.
 */

import android.os.AsyncTask;


import org.apache.http.HttpResponse;
import org.apache.http.NameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.params.HttpClientParams;
import org.apache.http.impl.client.DefaultHttpClient;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.params.BasicHttpParams;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.CookieHandler;
import java.net.CookieManager;
import java.net.CookiePolicy;
import java.net.CookieStore;
import java.net.HttpCookie;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */


public class AuthValidator extends AsyncTask<String,Void,String> {
    private String password;
    private String username;
    private boolean result;
    private Vector<AuthListener> authListeners;

    public AuthValidator( String username, String password) {
        this.username = username;
        this.password = password;
        this.result = false;
        this.authListeners = new Vector<AuthListener>();
    }

    public void addListener(AuthListener r){
        authListeners.add(r);
    }

    public boolean getResult(){
        return this.result;
    }


    @Override
    protected void onPostExecute(String result) {
        int state = 1;
        if(result.equals("ok")){
            state = 0;
        }
        for(AuthListener listener : authListeners)
            listener.onResult(state);

    }

    @Override
    protected String doInBackground(String... params) {

        try {
            String cookie_j = "";
            CookieManager manager = new CookieManager();
            manager.setCookiePolicy(CookiePolicy.ACCEPT_ALL);
            CookieHandler.setDefault(manager);
            URL target = new URL("https://web.isen-bretagne.fr/cas/login?service=https://web.isen-bretagne.fr/uPortal/Login");
            URLConnection connection = target.openConnection();
            connection.setConnectTimeout(15 * 1000);
            InputStreamReader in = new InputStreamReader((InputStream) connection.getContent());
            BufferedReader buff = new BufferedReader(in);
            String line;
            String content = "";
            do {
                line = buff.readLine();
                content += line;
            } while (line != null);
            CookieStore cookieJar =  manager.getCookieStore();
            List<HttpCookie> cookies = cookieJar.getCookies();
            for (HttpCookie cookie: cookies) {
                cookie_j = cookie.getValue();
            }
            System.out.println("cookie : " + cookie_j);
            System.out.println("content : " + content);
            String strUrl = "https://web.isen-bretagne.fr/cas/login;jsessionid=" + cookie_j + "?service=https://web.isen-bretagne.fr/uPortal/Login";

            String[] results = content.split("name=\"lt\" value=\"");
            System.out.println(results[1]);
            String[] results2 = null;
            if(results.length==2 && cookie_j.length() == 32){
                results2 = results[1].split("\"");
                if(results2.length>1) {
                    String lt = results2[0];
                    System.out.println("lt : " + lt);
                    if(lt.length() == 76)
                        result = sendPost(strUrl, lt);
                }
            }


        } catch (Exception e) {
            return "ko";
        }
        return "ok";
    }

    private boolean sendPost(String url, String lt) throws Exception {
        BasicHttpParams httpParams = new BasicHttpParams();
        HttpClientParams.setRedirecting(httpParams, false);
        DefaultHttpClient httpclient = new DefaultHttpClient(httpParams);
        HttpPost httppost = new HttpPost(url);
        System.out.println("us : " + username + " psw : " + password + " lt : " + lt);
        ArrayList<NameValuePair> params = new ArrayList<NameValuePair>(0x4);
        params.add(new BasicNameValuePair("username", username));
        params.add(new BasicNameValuePair("password", password));
        params.add(new BasicNameValuePair("lt", lt));
        params.add(new BasicNameValuePair("_eventId", "submit"));
        httppost.setEntity(new UrlEncodedFormEntity(params, "UTF-8"));
        HttpResponse response = httpclient.execute(httppost);
        System.out.println(response.getStatusLine().toString());
        return response.getStatusLine().toString().contains(" 302 ");
    }

    protected void onPreExecute() {
    }

    protected void onProgressUpdate(Void[] values) {
    }

}

