#identifiants db
database:
  driver:  mysql
  host:  localhost
  username:  foyer
  password:  foyer
  database: foyer
  charset:  utf8
  collation:  utf8_unicode_ci
  prefix:  

#ce dossier doit après contenir un dossier product et mobile
dir_files: files/

#login de l'api
api_user: 
  root: s3curit3
  mobile: s3curit3

#hosts pouvants se connecter à la db sans connexion
hotsts_allows: [localhost, foyer.p4ul.tk, http://192.168.1.16]

#message des nofitications
notification:
  command: 
    state_0: Delete
    state_1: En cours de validation
    state_2: Validée
    state_3: Payée